/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    DonutChart: typeof import('./src/components/DonutChart.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Paginator: typeof import('./src/components/Paginator.vue')['default']
    PureButton: typeof import('./src/components/PureButton.vue')['default']
    PurePaginator: typeof import('./src/components/PurePaginator.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Spinner: typeof import('./src/components/Spinner.vue')['default']
  }
}
